Description: >-
  AWS CloudFormation Sample Template EC2Instance: Create
  an Amazon EC2 instance running the Amazon Linux AMI.
Parameters:
  EC2InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.

  EC2InstanceAmiId:
    Description: AMI for the EC2 instances
    Type: String
    Default: ami-0747e613a2a1ff483

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref EC2InstanceType
      ImageId: !Ref EC2InstanceAmiId


Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
